on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run tests
        run: cd ./tests && chmod +x run_tests.sh && ./run_tests.sh
        continue-on-error: false

      - name: Prepare files for GitHub Pages
        run: |
          mkdir -p ./_site
          rsync -av --progress index.html ./_site

      - name: Upload GitHub Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./_site

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
