name: Run Tests on Push

on:
  push:
    branches:
      - main  # or the branch you want to trigger the tests on

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Run tests
      run: |
        chmod +x ./run_tests.sh
        ./run_tests.sh
