name: Deploy static content to Pages

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  run-tests-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Step to run the tests
      - name: Run Tests
        run: |
          chmod +x ./run_tests.sh
          ./run_tests.sh

      # Only continue to deployment if the tests succeed
      - name: Setup Pages
        if: ${{ success() }}  # Deploy only if previous steps (tests) succeed
        uses: actions/configure-pages@v5

      - name: Upload artifact
        if: ${{ success() }}  # Deploy only if previous steps (tests) succeed
        uses: actions/upload-pages-artifact@v3
        with:
          path: '.'

      - name: Deploy to GitHub Pages
        if: ${{ success() }}  # Deploy only if previous steps (tests) succeed
        id: deployment
        uses: actions/deploy-pages@v4
